CREATE TABLE EMPLOYEE
( 
  FNAME text NOT NULL,
  MINITCHAR CHAR,
  LNAME text NOT NULL,
  SSN CHAR(9) NOT NULL,
  BDATE DATE,
  ADDRESS text,
  SEX CHAR,
  SUPERSSN CHAR(9),
  DNO INT,				
  PRIMARY KEY (SSN)  
);


CREATE TABLE DEPARTMENT
(
	DNAME text NOT NULL,
	DNUMBER INT NOT NULL,
	MGRSSN CHAR(9) NOT NULL, 
	MGRSTARTDATE DATE,
	PRIMARY KEY (DNUMBER),
	UNIQUE (DNAME),
	FOREIGN KEY (MGRSSN) REFERENCES EMPLOYEE(SSN)
);


CREATE TABLE DEPT_LOCATIONS
(
	DNUMBER INT NOT NULL,
	DLOCATION text NOT NULL,
	PRIMARY KEY (DNUMBER, DLOCATION),
	FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER)
	
);


CREATE TABLE PROJECT
(
	PNAME text NOT NULL,
	PNUMBER INT NOT NULL,
	PLOCATION text, 
	DNUM INT NOT NULL,
	PRIMARY KEY (PNUMBER),
	UNIQUE (PNAME),
	FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUMBER) 
	
);


CREATE TABLE WORKS_ON
( 
	ESSN CHAR(9) NOT NULL,
	PNO INT NOT NULL,
	HOURS DECIMAL(3,1),
	
	PRIMARY KEY (ESSN, PNO),
	FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN), 
	FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER) 
);


CREATE TABLE DEPENDENT
( 
	ESSN CHAR(9) NOT NULL ,
	DEPENDENT_NAME text NOT NULL,
	SEX CHAR,
	BDATE DATE,
	RELATIONSHIP text,
	PRIMARY KEY (ESSN, DEPENDENT_NAME),
	FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN) 
);